uav_model:
  dynamics_parameters:
    max_linear_velocity: 1.0
    max_linear_acceleration: 1.0
    max_yaw_velocity: 1.0471975512      # 60 degrees per second
    max_yaw_acceleration: 1.0471975512  # 60 degrees per second squared

  sensing_parameters:
    camera_intrinsics:
      fx: 320.0
      fy: 320.0
      cx: 320.0
      cy: 240.0
    image_width: 640
    image_height: 480
    min_depth: 0.1
    max_depth: 5.0
    fov:
      # RealSense D435 depth camera, Depth Field of View (FOV): 87° × 58°
      # https://www.intelrealsense.com/depth-camera-d435/
      horizontal: 1.518436449
      vertical: 0.994837673