astar:
  lambda_heuristic: 1.0
  unknown_penalty_factor: 2.0
  allocate_num: 100000
  epsilon: 0.0001 # 1e-4
  verbose: false

  profile:
    default:
      resolution: 0.5
      max_search_time: 0.001
    coarse:
      resolution: 1.0
      max_search_time: 0.0001
    coarse2:
      resolution: 1.0
      max_search_time: 0.001
    medium:
      resolution: 1.0
      max_search_time: 0.1
    fine:
      resolution: 0.1
      max_search_time: 0.1
